kind: Secret
apiVersion: v1
metadata:
  name: md-postgres-cred
  namespace: "{{ chart_values.app_name }}"
type: Opaque
data:
  user: "{{ chart_values.db_user | b64encode }}"
  password: "{{ chart_values.db_password | b64encode }}"