apiVersion: v1
kind: Secret
metadata:
  name: nms-credential
  namespace: "{{ extra_volterra_namespace }}"
type: Opaque
data:
  username: "{{ var_credential.username | b64encode }}"
  password: "{{ var_credential.password | b64encode }}"